import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white min-h-[100vh]">
        <div className="fixed top-0 left-0 w-full h-full  overflow-y-auto">
          <Header />
          <main className="max-w-[1000px] ml-auto mr-auto  pt-[200px] pb-[200px] w-full  px-2 lg:px-0">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
