import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-[100vh] bg-black text-white">
        <div className="fixed left-0 top-0 h-full w-full  overflow-y-auto">
          <Header />
          <main className="ml-auto mr-auto w-full  max-w-[1000px] px-2 pb-[200px]  pt-[200px] lg:px-0">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
